server:
  port: 8090

spring:
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://netcompany.database.windows.net:1433;databaseName=DB_Auth;encrypt=true;trustServerCertificate=false;loginTimeout=30;
    username: netcompany
    password: "@Isac922024126"

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
        format_sql: true

  hikari:
    maximum-pool-size: 10
    minimum-idle: 2
    idle-timeout: 30000
    connection-timeout: 30000
    pool-name: HikariPool-AuthService

  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8090

eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
  instance:
    prefer-ip-address: true

management:
  endpoints:
    web:
      exposure:
        include: "*"

logging:
  level:
    org.springframework.security: INFO
    com.netshop.auth_service: DEBUG
