server:
  port: 8080

spring:
  application:
    name: gateway-service
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          lower-case-service-id: true
      routes:
        # Ruta para productos
        - id: productos-service
          uri: lb://productos-service
          predicates:
            - Path=/api/productos/**

        - id: categorias-service
          uri: lb://productos-service
          predicates:
            - Path=/api/categorias/**
        # Ruta pública (login, registro)
        - id: auth-service
          uri: lb://auth-service
          predicates:
            - Path=/api/auth/**
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka
