server:
  port: 8100

spring:
  datasource:
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver
    url: jdbc:sqlserver://netcompany.database.windows.net:1433;database=DB_Productos;encrypt=true;trustServerCertificate=false;loginTimeout=30;
    username: netcompany
    password: "@Isac922024126" # Es mejor pr치ctica manejar esto con Spring Cloud Vault o Azure Key Vault.
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        dialect: org.hibernate.dialect.SQLServerDialect
  hikari:
    maximum-pool-size: 10
    minimum-idle: 2
    idle-timeout: 30000
    connection-timeout: 30000
    pool-name: HikariPool-NetShop

# Configuraci칩n para que este servicio se registre en Eureka.
eureka:
  client:
    serviceUrl:
      # Direcci칩n donde est치 corriendo tu servidor Eureka.
      defaultZone: http://localhost:8761/eureka/