server:
  port: 8110

spring:
  datasource:
    url: jdbc:sqlserver://netcompany.database.windows.net:1433;database=BD_Usuarios;encrypt=true;trustServerCertificate=false;loginTimeout=30;
    username: netcompany
    password: "@Isac922024126"
    driver-class-name: com.microsoft.sqlserver.jdbc.SQLServerDriver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.SQLServerDialect
        format_sql: true

  hikari:
    maximum-pool-size: 10
    minimum-idle: 2
    idle-timeout: 30000
    connection-timeout: 30000
    pool-name: HikariPool-NetShop

eureka:
  client:
    serviceUrl:
      # Dirección donde está corriendo tu servidor Eureka.
      defaultZone: http://localhost:8761/eureka/

